CREATE TABLE ROLE (
	`ID` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
	`DESCRIPTION` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE ROLE ADD CONSTRAINT UNIQUE (NAME);
INSERT INTO ROLE (ID, NAME, DESCRIPTION) VALUES (1, 'active user', 'All users need this to work.');
-- populating table roles
INSERT INTO ROLE (NAME, DESCRIPTION)
SELECT USERNAME, CONCAT('Role for user ', USERNAME) as DESCRIPTION FROM USER ;

CREATE TABLE ROLE_USER (
	`ROLE` int(11) NOT NULL,
    `USER` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE ROLE_USER ADD CONSTRAINT UNIQUE (ROLE,USER);
INSERT INTO ROLE_USER (ROLE,USER) 
SELECT ROLE.ID, USER.ID FROM ROLE,USER WHERE ROLE.NAME=USER.USERNAME;

-- ALL USERS ARE ACTIVE USERS
INSERT INTO ROLE_USER (ROLE,USER) 
SELECT 1, USER.ID FROM USER;


CREATE TABLE PERMISSION (
  `ID` int(11) NOT NULL auto_increment PRIMARY KEY,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO PERMISSION (ID, NAME, DESCRIPTION) VALUES (1, 'READ', 'read');
INSERT INTO PERMISSION (ID, NAME, DESCRIPTION) VALUES (2, 'WRITE', 'write');
INSERT INTO PERMISSION (ID, NAME, DESCRIPTION) VALUES (3, 'GRANT', 'grant');

CREATE TABLE TYPE_PERMISSION (
	`ID` int(11) NOT NULL auto_increment PRIMARY KEY,
	`ROLE` int(11) NOT NULL,
	`TYPE` int(11) NOT NULL,
	`PERMISSION` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE TYPE_PERMISSION
ADD CONSTRAINT FOREIGN KEY (TYPE) REFERENCES TYPE(ID) ON DELETE CASCADE,
ADD CONSTRAINT FOREIGN KEY (ROLE) REFERENCES ROLE(ID) ON DELETE CASCADE,
ADD CONSTRAINT FOREIGN KEY (PERMISSION) REFERENCES PERMISSION(ID) ON DELETE CASCADE;

CREATE TABLE CONTEXT_PERMISSION (
	`ID` int(11) NOT NULL auto_increment PRIMARY KEY,
	`ROLE` int(11) NOT NULL,
	`CONTEXT` int(11) NOT NULL,
	`PERMISSION` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE CONTEXT_PERMISSION
ADD CONSTRAINT FOREIGN KEY (CONTEXT) REFERENCES CONTEXT(ID) ON DELETE CASCADE,
ADD CONSTRAINT FOREIGN KEY (ROLE) REFERENCES ROLE(ID) ON DELETE CASCADE,
ADD CONSTRAINT FOREIGN KEY (PERMISSION) REFERENCES PERMISSION(ID) ON DELETE CASCADE;

CREATE TABLE TAXONOMY_PERMISSION (
	`ID` int(11) NOT NULL auto_increment PRIMARY KEY,
	`ROLE` int(11) NOT NULL,
	`TAXONOMY` int(11) NOT NULL,
	`PERMISSION` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE TAXONOMY_PERMISSION
ADD CONSTRAINT FOREIGN KEY (TAXONOMY) REFERENCES TAXONOMY(ID) ON DELETE CASCADE,
ADD CONSTRAINT FOREIGN KEY (ROLE) REFERENCES ROLE(ID) ON DELETE CASCADE,
ADD CONSTRAINT FOREIGN KEY (PERMISSION) REFERENCES PERMISSION(ID) ON DELETE CASCADE;


CREATE TABLE EXPORTPROFILE_PERMISSION (
	`ID` int(11) NOT NULL auto_increment PRIMARY KEY,
	`ROLE` int(11) NOT NULL,
	`EXPORTPROFILE` int(11) NOT NULL,
	`PERMISSION` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE EXPORTPROFILE_PERMISSION
ADD CONSTRAINT FOREIGN KEY (EXPORTPROFILE) REFERENCES EXPORTPROFILE(ID) ON DELETE CASCADE,
ADD CONSTRAINT FOREIGN KEY (ROLE) REFERENCES ROLE(ID) ON DELETE CASCADE,
ADD CONSTRAINT FOREIGN KEY (PERMISSION) REFERENCES PERMISSION(ID) ON DELETE CASCADE;
