-- CREATE A NEW USER
INSERT INTO USER (USERNAME,PASSWORD) VALUES ('demo1', 'demo1');
INSERT INTO ROLE (NAME,DESCRIPTION) VALUES ('demo1','Role for user demo1');
INSERT INTO ROLE_USER (ROLE, USER) 
SELECT ROLE.ID,USER.ID FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME='demo1';
-- ACTIVATE USER
INSERT INTO ROLE_USER (ROLE,USER) SELECT 1, USER.ID FROM USER WHERE USERNAME='demo1'; 


-- GRANT WRITE on TAXONOMY to USER
INSERT IGNORE INTO TAXONOMY_PERMISSION (PERMISSION, ROLE, TAXONOMY)
SELECT 2, ROLE.ID, 1 FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu');
INSERT IGNORE INTO TAXONOMY_PERMISSION (PERMISSION, ROLE, TAXONOMY)
SELECT 2, ROLE.ID, 11 FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu');
INSERT IGNORE INTO TAXONOMY_PERMISSION (PERMISSION, ROLE, TAXONOMY)
SELECT 2, ROLE.ID, 12 FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu');
INSERT IGNORE INTO TAXONOMY_PERMISSION (PERMISSION, ROLE, TAXONOMY)
SELECT 2, ROLE.ID, 15 FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu');

-- GRANT WRITE on CONTEXT to USER
INSERT IGNORE INTO CONTEXT_PERMISSION (PERMISSION, ROLE, CONTEXT)
SELECT 2, ROLE.ID, 54 FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu');
SELECT 2, ROLE.ID, 65 FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu');
SELECT 2, ROLE.ID, 66 FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu');
SELECT 2, ROLE.ID, 67 FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu');

-- GRANT WRITE TO ANY TYPE
INSERT IGNORE INTO TYPE_PERMISSION (PERMISSION, ROLE, TYPE)
SELECT 2, ROLE.ID, TYPE.ID 
    FROM ROLE INNER JOIN USER ON ROLE.NAME=USER.USERNAME WHERE ROLE.NAME IN ('enrico', 'mathieu'),
	TYPE
