<form method="post" class="panel panel-default" action="?">
	<input type="hidden" name="controller" value="contexts" /> <input
		type="hidden" name="action" value="posteditcontext" /> <input
		type="hidden" name="context" value="<?php print $this->get('id'); ?>" />
	<div class="panel-heading">Edit context</div>
	<!-- 		<div class="panel-body"></div> -->
	<ul class="list-group">
		<li class="list-group-item">
			<div class="input-group">
				<label class="input-group-addon" for="name">Name</label> <input
					class="form-control" type="text" name="name"
					value="<?php print $this->get('name','');?>" />
			</div>
		</li>
		<li class="list-group-item">
			<div class="input-group">
				<label class="input-group-addon" for="name">Description</label> <textarea
					class="form-control" name="description"><?php print $this->get('description','');?></textarea>
			</div>
		</li>
		<li class="list-group-item">
			<div class="input-group">
				<label class="input-group-addon" for="name">Objects</label> <input
					readonly class="form-control" type="text"
					value="<?php print $this->get('objects_name'); ?>" />
			</div>
		</li>

		<li class="list-group-item">
			<div class="input-group">
				<label class="input-group-addon" for="name">Attributes</label> <input
					readonly class="form-control" type="text"
					value="<?php print $this->get('attributes_name'); ?>" />
			</div>
		</li>
		<li class="list-group-item">
			<div class="input-group">
				<button class="btn btn-default" type="submit">Submit</button>
			</div>
		</li>
	</ul>
</form>
