<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Log</div>
		<div class="panel-body"></div>
		<table class="table">
			<thead>
				<tr>
					<th>#ID</th>
					<th>Time</th>
					<th>User</th>
					<th>Changed</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->get('log',array()) as $log): ?>
				<tr>
					<td><?php print $log['id'] ?></td>
					<td><?php print $log['time'] ?></td>
					<td><?php print $log['username'] ?></td>
					<td><?php print $log['changes'] ?></td>
					<td>
					<a href="<?php print route('logs', 'logdetails', array('context' => $log['context'], 'logaction' => $log['id'])); ?>"
								class="btn btn-default btn-xs ">
								<span class="glyphicon glyphicon-list"></span>
							</a>
							
					</td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
</div>
	